//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Email_Generator.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public Issue()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int Id { get; set; }
        public string Semester { get; set; }
        public int Year { get; set; }
        public int Volume { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
    }
}
